export const data = [
  {
    name: 'urs',
    last_login: '2022-06-28',
    last_edit: '2022-06-20',
    months: [
      { numberLogins: 31, numberEdits: 3, monthName: 'Januar' },
      { numberLogins: 36, numberEdits: 6, monthName: 'Februar' },
      { numberLogins: 26, numberEdits: 5, monthName: 'März' },
      { numberLogins: 25, numberEdits: 36, monthName: 'April' },
      { numberLogins: 17, numberEdits: 33, monthName: 'Mai' },
      { numberLogins: 16, numberEdits: 17, monthName: 'Juni' },
      { numberLogins: 24, numberEdits: 17, monthName: 'Juli' },
      { numberLogins: 26, numberEdits: 37, monthName: 'August' },
      { numberLogins: 18, numberEdits: 16, monthName: 'September' },
      { numberLogins: 33, numberEdits: 32, monthName: 'Oktober' },
      { numberLogins: 21, numberEdits: 16, monthName: 'November' },
      { numberLogins: 27, numberEdits: 19, monthName: 'Dezember' },
    ],
  },
  {
    name: 'Nick',
    last_login: '2022-08-10',
    last_edit: '2022-08-9',
    months: [
      { numberLogins: 3, numberEdits: 3, monthName: 'Januar' },
      { numberLogins: 5, numberEdits: 6, monthName: 'Februar' },
      { numberLogins: 6, numberEdits: 5, monthName: 'März' },
      { numberLogins: 35, numberEdits: 36, monthName: 'April' },
      { numberLogins: 7, numberEdits: 23, monthName: 'Mai' },
      { numberLogins: 13, numberEdits: 18, monthName: 'Juni' },
      { numberLogins: 34, numberEdits: 27, monthName: 'Juli' },
      { numberLogins: 25, numberEdits: 31, monthName: 'August' },
      { numberLogins: 8, numberEdits: 6, monthName: 'September' },
      { numberLogins: 23, numberEdits: 22, monthName: 'Oktober' },
      { numberLogins: 2, numberEdits: 14, monthName: 'November' },
      { numberLogins: 17, numberEdits: 9, monthName: 'Dezember' },
    ],
  },
  {
    name: 'pia',
    last_login: '2022-07-3',
    last_edit: '2022-07-3',
    months: [
      { numberLogins: 13, numberEdits: 13, monthName: 'Januar' },
      { numberLogins: 25, numberEdits: 6, monthName: 'Februar' },
      { numberLogins: 26, numberEdits: 51, monthName: 'März' },
      { numberLogins: 45, numberEdits: 50, monthName: 'April' },
      { numberLogins: 27, numberEdits: 28, monthName: 'Mai' },
      { numberLogins: 23, numberEdits: 18, monthName: 'Juni' },
      { numberLogins: 44, numberEdits: 43, monthName: 'Juli' },
      { numberLogins: 35, numberEdits: 36, monthName: 'August' },
      { numberLogins: 19, numberEdits: 16, monthName: 'September' },
      { numberLogins: 28, numberEdits: 22, monthName: 'Oktober' },
      { numberLogins: 23, numberEdits: 18, monthName: 'November' },
      { numberLogins: 15, numberEdits: 19, monthName: 'Dezember' },
    ],
  },
  {
    name: 'Patrick',
    last_login: '2022-05-18',
    last_edit: '2022-05-18',
    activities: [{ name: '1. activity' }, { name: '1. activity' }],
    months: [
      { numberLogins: 31, numberEdits: 3, monthName: 'Januar' },
      { numberLogins: 25, numberEdits: 6, monthName: 'Februar' },
      { numberLogins: 36, numberEdits: 5, monthName: 'März' },
      { numberLogins: 39, numberEdits: 36, monthName: 'April' },
      { numberLogins: 17, numberEdits: 23, monthName: 'Mai' },
      { numberLogins: 17, numberEdits: 18, monthName: 'Juni' },
      { numberLogins: 64, numberEdits: 27, monthName: 'Juli' },
      { numberLogins: 25, numberEdits: 39, monthName: 'August' },
      { numberLogins: 8, numberEdits: 9, monthName: 'September' },
      { numberLogins: 31, numberEdits: 31, monthName: 'Oktober' },
      { numberLogins: 68, numberEdits: 72, monthName: 'November' },
      { numberLogins: 17, numberEdits: 9, monthName: 'Dezember' },
    ],
  },

  {
    name: 'aaron',
    last_login: '2022-04-13',
    last_edit: '2022-04-11',
    months: [
      { numberLogins: 3, numberEdits: 3, monthName: 'Januar' },
      { numberLogins: 65, numberEdits: 68, monthName: 'Februar' },
      { numberLogins: 26, numberEdits: 35, monthName: 'März' },
      { numberLogins: 32, numberEdits: 36, monthName: 'April' },
      { numberLogins: 32, numberEdits: 24, monthName: 'Mai' },
      { numberLogins: 31, numberEdits: 42, monthName: 'Juni' },
      { numberLogins: 34, numberEdits: 27, monthName: 'Juli' },
      { numberLogins: 25, numberEdits: 31, monthName: 'August' },
      { numberLogins: 8, numberEdits: 6, monthName: 'September' },
      { numberLogins: 23, numberEdits: 22, monthName: 'Oktober' },
      { numberLogins: 2, numberEdits: 14, monthName: 'November' },
      { numberLogins: 17, numberEdits: 9, monthName: 'Dezember' },
    ],
  },
];
